pipeline{
    agent{
        docker {
            image 'thanhtha/jenkins-agent:java-v17-mvn-npm-2'
            args '-u root:root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    stages{
        stage('Checkout') {
            steps {
                echo "========checking out dev branch code========"
                // CHỈ LẤY MÃ TỪ BRANCH dev
                checkout([$class: 'GitSCM',
                    branches: [[name: "*/dev"]],
                    userRemoteConfigs: [[url: 'https://github.com/tnubeo1111/cicd-repo.git']]
                ])
            }
        }
        stage("B"){
            steps{
                echo "========executing B========"
            }  
        }
        stage("C"){
            steps{
                echo "========executing C========"
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}