apiVersion: v1
kind: Service
metadata:
  name: to-do-list
  labels:
    app: to-do-list
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30082
    protocol: TCP
    name: http
  selector:
    app: to-do-list