apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-list
  labels:
    app: to-do-list
spec:
  replicas: 2
  selector:
    matchLabels:
      app: to-do-list
  template:
    metadata:
      labels:
        app: to-do-list
    spec:
      containers:
      - name: to-do-list
        image: thanhtha/to-do-list:8
        # Image will be automatically updated by CI/CD pipeline
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
