pipeline {
    agent {
        docker {
            image 'thanhtha/jenkins-agent:java-v17-mvn-npm-1'
            args '--user root -v /var/run/docker.sock:/var/run/docker.sock' // mount Docker socket to access the host's Docker daemon
        }
    }
    stages {
        stage ('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/tnubeo1111/cicd-repo.git'
            }
        }
        stage ('Check Directory Dest') {
            steps {
                sh '''
                    cd node-npm-sonar-argocd-k8s/tic-tac
                    if [ ! -d "Dest" ]; then
                        echo "Directory 'tic-tac' does not exist."
                    fi

                    ls -al
                '''
            }
        }
    }
    post {
      always {
        cleanWs()
      }
    }
}