# Generated by Django 3.0.5 on 2021-08-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtask',
            name='time',
            field=models.TimeField(),
        ),
    ]
