# Generated by Django 3.0.5 on 2021-08-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newtask_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newtask',
            name='Check',
        ),
    ]
